### PR TITLE
Trim Spaces Left After Removing Invalid Characters

### PR DESCRIPTION
**Pull request by bgerhards**
What?
Trims spaces left in the line data after sanitizing.

Why?
After sanitizing the data, extra spaces may be left that need to be trimmed off. This is causing the text ANSI to not be recognized still.

### CODE REVIEW

**Comment by mvayngrib** [comment]
@bgerhards  could you rebase your changes over master? Also, any reason you drastically simplified the tests?

**Comment by bgerhards** [comment]
I didn't realize you rebased your commits. My fork is out of sync. Without killing my fork it won't be pretty. I live on the premise that rebasing master is forbidden because of issues like this. I can rebase commits on any future pull requests if you would like (when there are more than one commits unlike this one, which has only one commit). On that, I'm also against rebasing, but I will rebase if you want me to.

So I thought about moving all of the expect statements to another function, but then I wanted to remove unnecessary tests. What the tests are trying to prove is that an object is created with the data that is provided. With the data tests, the first test is being replicated, but with the count, it's simply proving that the object has been rendered with X number of keys.

**Comment by mvayngrib** [comment]
i usually squash and merge PRs. It's just confusing to see 12 commits in this PR when it's really 1. I can squash and merge this one, but for the next one please pre-squash!

with the tests, why not just simplify to `expect(parsed).to.deepEqual(expectedData)`? Where `expectedData` is some global, or separate fixture json

**Comment by bgerhards** [comment]
I updated the tests as you requested. That is indeed a better idea. I squashed it with the previous commit.

**Comment by mvayngrib** [comment]
cool, merged/released (2.0.2)

**Pull request merged**
