### PR TITLE
Clean Code, Add Tests, Suppress Error

### PR DESCRIPTION
**Pull request by bgerhards**
USDL PDF417 do not all seem to have the same code outputs. I find an Iowa license to be displaying codes not found in the official documentation. This raised a red flag when errors began appearing when I started to try parsing the data. I do not want the errors to appear, so I added a default disabling of the errors that are related to a missing key. This is an easy addition to the options when calling the `parse` method.

I also added a few simple tests with Jest along side Babel to ensure ES* compilation at test time.

Organized the code a little bit and removed unnecessary files.

### CODE REVIEW

**Comment by bgerhards** [comment]
Suppressing errors would still allow the parsing to continue building the object with the information it has without blowing up. This will provide fields as undefined organically but will also allow for future changes to the USDL without immediate changes to the repo. A try/catch would not provide any information that may have been collected by the program because an error was raised. Maybe suppressing the warning should not happen automatically.

Transpilation is not happening the way you may think it is. I have Babel in there but only for testing with Jest.

**Comment by mvayngrib** [comment]
re: suppressErrors: i see, that makes sense! However, let's make it default to `false`
re: transpilation: you're using `import` in `parseUsdl.js` and `export` in `index.js`, which requires transpilation i'm pretty sure.

**Comment by bgerhards** [comment]
Do you have a scenario where this would be used without a transpiler? It's already in ES6 so if someone wanted to use this they would need something that has the power built in.

**Comment by mvayngrib** [comment]
i think currently the only es6 code is the use of `const`, which is supported in most browsers, and versions of node. i don't think `import` is supported anywhere natively yet

**Comment by mvayngrib** [comment]
@bgerhards thanks for reverting to es5

question: why `lines.slice(0, -1)`? Is the last line guaranteed to be something useless?

also, some of the tests are failing

**Comment by bgerhards** [comment]
Thanks for the info. Based on your sample provided in the ReadMe, you have a ZDF code as the final line:

`ZNZNAMDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5`

This code is not an acceptable code per the document referenced. This is partially the reason behind why I personally prefer an error suppression. It is working on all ID's that I can scanned because last code has not shown up in the database, but that may be coincidence. I removed the removal of the final line but in turn had to modify the sample code in the tests.

I am not having any issues with the date formatting, all of the tests are passing. I did modify the getDateFormat to be similar because it is simple. If you're referring to the format, I assumed that was your expected. I have updated it to output it to be a string in a `mm/dd/yyyy` format.

**Comment by mvayngrib** [comment]
ah, i see, i had the same thing, in a different format: `for (let i = 0; i < lines.length - 1; i++) {`

my bad! please return the `slice(0, -1)`. If that's the format that comes from scanning the barcode, then that's what we should handle. For reference, the spec is here: 

[2016 Card Design Standard.pdf](https://github.com/mvayngrib/parse-usdl/files/2108367/2016.Card.Design.Standard.pdf) on page 61. Source: https://www.aamva.org/DL-ID-Card-Design-Standard/

i'm ok with error suppression as long as it's not the default. I don't want to silently return partially complete values for invalid USDL input texts, or if someone puts in their chicken pot pie recipe.

**Comment by mvayngrib** [comment]
i just tried scanning my own driver license

- you're right about a bunch of codes not included here! Maybe they're specific to my state
- it also has that last line of nonsense, though different nonsense than in the example

**Comment by mvayngrib** [comment]
maybe we can find a source/spec for these extra codes

**Comment by mvayngrib** [comment]
@bgerhards merged, thanks! Will release as 2.0.0 as date format changed

**Pull request merged**
