### PR TITLE
Supports Ontario drivers licenses

### PR DESCRIPTION
**Pull request by aeisenberg**
Possibly other Canadian driver's licenses as well, but not tested.

Includes unit tests.

### CODE REVIEW

**Comment by aeisenberg** [comment]
Fixes #9.

**Comment by aeisenberg** [comment]
The data I am using for the Ontario license is derived directly from scans we've done of existing licenses. So, the fields that you see are the ones that exist in real licenses. Unfortunately, there's no online link that I have found for this, and for privacy reasons, I don't want to include photos of the licenses we've scanned.

Note that Ontario uses the `givenName` field instead of the `firstName` field.

**Comment by mvayngrib** [comment]
> Note that Ontario uses the givenName field instead of the firstName field.

is there any reason not to map both to firstName?

**Comment by forivall** [comment]
@mvayngrib yeah, givenName can include the middle name.

**Pull request closed without merging**
